import { InferGetServerSidePropsType, type GetServerSideProps, type NextPage } from "next";
import { getSession } from "next-auth/react";
import Head from "next/head";

import Image from "next/image";

import { NavBar, Notifs } from "~/components/barrel";
import { PromoWithAll } from "~/utils/type";
import { prisma } from "~/server/db";
import { BiGroup, BiCalendar } from "react-icons/bi";
import { aleatoirePP } from "~/utils/genertor";
import Link from "next/link";


export const getServerSideProps: GetServerSideProps<{
    promo: PromoWithAll
}> = async function (context) {
    const session = await getSession(context)
    const admin = session?.formateur
    const superadmin = session?.superadmin

    if (!session) {
        return {
            redirect: {
                destination: '/login',
                permanent: false,
            },
        }
    }

    if (!superadmin || !admin) {
        return {
            redirect: {
                destination: '/',
                permanent: false,
            },
        }
    }

    const promo = await prisma.promo.findUnique({
        where: {
            id: context.query.id as string
        },
        include: {
            apprenants: true,
            referentiel: true
        }
    })

    if (!promo) {
        return {
            redirect: {
                destination: '/admin/promo',
                permanent: false,
            },
        }
    }

    return {
        props: {
            promo: JSON.parse(JSON.stringify(promo)) as PromoWithAll
        }
    }
};

const idPromo: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = ({ promo }) => {

    let img = "/logo-gradient.jpg"
    if (promo.image !== "") {
        img = promo.image
    }

    return (
        <>
            <Head>
                <title>{promo.title}</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-start bg-[#F3F3F3] pl-[150px] pr-[200px] px-[50px] py-10 gap-5">

                <section className="flex w-full flex-col items-center justify-start bg-white px-[40px] py-[40px] gap-5 rounded-xl">
                    <div id="haut" className="flex items-center w-full gap-5 justify-center">
                        <Image width={500} height={500} loader={() => img} src={img} className="w-[55%] h-[300px] h-auto object-cover mr-5 rounded-lg" alt="Image de la promo sélectionnée" />
                        <aside className="flex flex-col justify-start gap-3">
                            <h3 className="text-xl text-black mb-2">{promo.title}</h3>
                            <button className={`w-[80%] py-4 px-4 shadow-[3px_4px_12px_0px_rgba(0,0,0,0.25)] text-center text-md rounded-lg bg-white hover:cursor-pointer`}>{promo.referentiel.title}</button>
                            <span className="flex w-full flex-row items-center justify-between">
                                <span className="flex w-full flex-row items-center">
                                    <BiGroup className="text-4xl text-[#0E6073] mr-1" />
                                    <p>{promo && promo.apprenants ? promo.apprenants.length : "0"} apprenants</p>
                                </span>
                                <span className="flex w-full flex-row items-center">
                                    <BiCalendar className="text-4xl text-[#0E6073] mr-1" />
                                    <p>Du {promo.starting.toString().slice(0,10).replaceAll('-','/')} au {promo.ending.toString().slice(0,10).replaceAll('-','/')}</p>
                                </span>
                            </span>

                        </aside>

                    </div>
                    <div id="bas" className="flex items-start w-full">
                        <aside className="w-[50%]">
                            <h3 className="text-xl text-black mb-2">Description</h3>
                            <div dangerouslySetInnerHTML={{ __html: promo.description }} />
                        </aside>
                        <aside className="grid grid-cols-2 w-[50%]">
                            {promo.apprenants.length > 0 && promo.apprenants.map((item) => {
                                let pp = aleatoirePP()
                                if (item.image !== "" && item.image !== null) {
                                    pp = item.image
                                }
                                return (
                                    <Link href={`/superadmin/users/${item.id}`} className="flex flex-row justify-end items-center w-full mt-5" key={item.id}>
                                        <Image width={300} height={300} loader={() => pp} src={pp} className="w-12 h-12 rounded-full object-cover mr-3" alt="Photo de profil utilisateur" />
                                        <p className="text-sm text-black">{item.firstName} {item.name}</p>
                                    </Link>)
                            })}
                        </aside>

                    </div>
                </section>


                <Notifs />
                <NavBar />
            </main>
        </>
    );
};

export default idPromo;