import { type GetServerSideProps, type NextPage } from "next";
import { getSession } from "next-auth/react";
import Head from "next/head";
import { PieChart, Pie, Label, Cell, Legend } from 'recharts';

import { type Session as SessionAuth } from 'next-auth'

import { NavBar, Notifs, Promos } from "~/components/barrel";
import { BiChevronDown, BiSearch } from "react-icons/bi";
import Image from "next/image";
import React, { useState, PureComponent } from "react";


export const getServerSideProps: GetServerSideProps<{
    session: SessionAuth
}> = async function (context) {
    const session = await getSession(context)
    const superadmin = session?.superadmin

    if (!session) {
        return {
            redirect: {
                destination: '/login',
                permanent: false,
            },
        }
    }

    if (!superadmin) {
        return {
            redirect: {
                destination: '/',
                permanent: false,
            },
        }
    }

    return {
        props: { session }
    }
};

const IndexPromo: NextPage = () => {

    const data = [
        { name: 'Group A', value: 58, fill: '#2EA3A5' },
        { name: 'Group B', value: 42, fill: "#D9D9D9" },
      ];
    const [open, setOpen] = useState(false)

    return (
        <>
            <Head>
                <title>Gestion de OktoBrief</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-start justify-start bg-[#F3F3F3] pl-[100px]">
                <div className="flex min-h-screen w-full flex-col items-start justify-start px-10 pt-[40px]">
                    <div className="self-end mb-5">
                        <Promos />
                    </div>
                    <span className="flex w-[80%] flex-row items-center justify-between mb-5 pl-10">
                        <h1 className="text-4xl font-extrabold text-black">Les promos</h1>
                        <div className="pr-[1rem] rounded-full bg-white shadow-[inset_4px_4px_12px_4px_rgba(0,0,0,0.25)] w-[30%] flex flex-row justify-between items-center">
                            <BiSearch className="text-3xl text-black ml-4" />
                            <input
                                type='text'
                                name="promoDateStart"
                                className="pr-[1rem] pl-1 py-3 w-full bg-transparent"
                                autoComplete="off"
                            />
                        </div>
                    </span>

                    <div className="w-full flex flex-row justify-between">
                        <div className="flex w-[80%] flex-col items-center justify-start bg-white p-10 mb-5 rounded-xl">
                            <span className="flex w-full flex-row items-center justify-between mb-3">
                                <span className="flex w-[45%] flex-row items-center justify-start">
                                    <button className="text-sm text-black bg-[#EDEDED] rounded-full px-5 py-3 mr-2">Actives</button>
                                    <button className="text-sm text-black bg-[#EDEDED] rounded-full px-5 py-3 mr-2">Inactives</button>
                                </span>
                                <span className="flex w-[60%] flex-row items-center justify-end">
                                    <div className="relative">
                                        <button className="flex flex-row items-center justify-between px-5 py-2 bg-[#0E6073] text-white rounded-lg" onClick={() => setOpen(!open)}>
                                            <p className="text-base mr-2">Tri par: Date de début</p>
                                            <BiChevronDown className="text-4xl" />
                                        </button>
                                        {open &&
                                            <div className="w-full absolute bg-white rounded-b-lg flex flex-col items-center divide-y divide-[#0E6073]">
                                                <button className="text-sm text-[#0E6073] py-4">Promo 2 2022/2023</button>
                                                <button className="text-sm text-[#0E6073] py-4">Promo 3 2022/2023</button>
                                                <button className="text-sm text-[#0E6073] py-4">Promo 4 2022/2023</button>
                                            </div>
                                        }
                                    </div>
                                    <button className="flex flex-row items-center justify-between px-5 py-3 ml-4 bg-[#2EA3A5] hover:bg-[#288F90] text-white rounded-lg text-base">
                                        Créer une promo
                                    </button>
                                </span>
                            </span>

                            <div className="flex gap-3">
                                <div className="flex flex-col drop-shadow-md w-[35%] bg-white rounded-xl gap-3">
                                    <div className="w-full h-[170px]"><Image width={300} height={300} src="/promo.jpeg" className="w-full h-full object-cover rounded-t-xl" alt="Image de la promo sélectionnée" /></div>
                                    <h3 className="text-[20px] px-5">Promo 1 2022/2023</h3>
                                    <p className="text-[14px] px-5 pb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sodales euismod blandit.</p>
                                </div>

                                <div className="flex flex-col drop-shadow-md w-[35%] bg-white rounded-xl gap-3">
                                    <div className="w-full h-[170px]"><Image width={300} height={300} src="/promo.jpeg" className="w-full h-full object-cover rounded-t-xl" alt="Image de la promo sélectionnée" /></div>
                                    <h3 className="text-[20px] px-5">Promo 1 2022/2023</h3>
                                    <p className="text-[14px] px-5 pb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sodales euismod blandit.</p>
                                </div>

                                <div className="flex flex-col drop-shadow-md w-[35%] bg-white rounded-xl gap-3">
                                    <div className="w-full h-[170px]"><Image width={300} height={300} src="/promo.jpeg" className="w-full h-full object-cover rounded-t-xl" alt="Image de la promo sélectionnée" /></div>
                                    <h3 className="text-[20px] px-5">Promo 1 2022/2023</h3>
                                    <p className="text-[14px] px-5 pb-5 test">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sodales euismod blandit.</p>
                                </div>
                            </div>
                            <div className="flex gap-3">
                                <div className="flex flex-col drop-shadow-md w-[35%] bg-white rounded-xl gap-3">
                                    <div className="w-full h-[170px]"><Image width={300} height={300} src="/promo.jpeg" className="w-full h-full object-cover rounded-t-xl" alt="Image de la promo sélectionnée" /></div>
                                    <h3 className="text-[20px] px-5">Promo 1 2022/2023</h3>
                                    <p className="text-[14px] px-5 pb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sodales euismod blandit.</p>
                                </div>

                                <div className="flex flex-col drop-shadow-md w-[35%] bg-white rounded-xl gap-3">
                                    <div className="w-full h-[170px]"><Image width={300} height={300} src="/promo.jpeg" className="w-full h-full object-cover rounded-t-xl" alt="Image de la promo sélectionnée" /></div>
                                    <h3 className="text-[20px] px-5">Promo 1 2022/2023</h3>
                                    <p className="text-[14px] px-5 pb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sodales euismod blandit.</p>
                                </div>

                                <div className="flex flex-col drop-shadow-md w-[35%] bg-white rounded-xl gap-3">
                                    <div className="w-full h-[170px]"><Image width={300} height={300} src="/promo.jpeg" className="w-full h-full object-cover rounded-t-xl" alt="Image de la promo sélectionnée" /></div>
                                    <h3 className="text-[20px] px-5">Promo 1 2022/2023</h3>
                                    <p className="text-[14px] px-5 pb-5 test">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sodales euismod blandit.</p>
                                </div>
                            </div>
                        </div>
                        <div className="flex w-[19%] flex-col items-center justify-start bg-white h-fit p-5 py-10 mb-5 rounded-xl">
                            <div className="flex flex-col items-center justify-center">
                                <h3 className="text-6xl mb-2 text-[#2EA3A5]">26</h3>
                                <p className="text-2xl mb-5 text-[#0E6073]">Promotions créées</p>
                            </div>
                            <div className="flex flex-col items-center justify-center relative">
                                <div className="flex flex-col items-center justify-center absolute">
                                    <h3 className="text-4xl text-[#0E6073]">{data[0]?.value}%</h3>
                                    <p className="text-base mb-1 text-[#0E6073]">Promos actives</p>
                                </div>
                                <PieChart width={200} height={200}>
                                    <p className="text-black text-2xl">test</p>
                                    <Pie
                                    data={[{ value: 100 }]} dataKey="value" innerRadius={75} outerRadius={95} fill="#D9D9D9" isAnimationActive={false} 
                                    />
                                    <Pie
                                    data={data}
                                    cx="50%"
                                    cy="50%"
                                    innerRadius={75}
                                    outerRadius={95}
                                    startAngle={90}
                                    endAngle={450}
                                    cornerRadius={90}
                                    paddingAngle={0}
                                    dataKey="value"
                                    stroke="none"
                                    >
                                    {data.map((entry, index) => (
                                        <Cell key={`cell-${index}`} fill={entry.fill} />
                                    ))}
                                    </Pie>
                                    
                                </PieChart>
                                
                            </div>
                        </div>
                    </div>
                </div>
                <Notifs />
                <NavBar />
            </main>
        </>
    );
};

export default IndexPromo;