import { type GetServerSideProps, type NextPage } from "next";
import { getSession } from "next-auth/react";
import Head from "next/head";

import { type Session as SessionAuth } from 'next-auth'

import { NavBar, Notifs } from "~/components/barrel";
import { BiLeftArrowAlt, BiLink, BiCheck } from "react-icons/bi";
import { IoChevronUpCircleSharp, IoChevronDownCircleSharp } from "react-icons/io5";

import Link from "next/link";
import { useState } from "react";


export const getServerSideProps: GetServerSideProps<{
    session: SessionAuth
}> = async function (context) {
    const session = await getSession(context)

    if (!session) {
        return {
            redirect: {
                destination: '/login',
                permanent: false,
            },
        }
    }

    return {
        props: { session }
    }
};

const Brief: NextPage = () => {
    const [open, setOpen] = useState(true)

    return (
        <>
            <Head>
                <title>Gestion de OktoBrief</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <main className="flex min-h-screen flex-col items-center justify-start bg-[#F3F3F3] pl-[150px] px-[50px] gap-5">
                <img src="/promo.jpeg" className="w-[100%] h-[400px] absolute bg-center bg-cover z-0" alt="Image de la promo sélectionnée" />
                <Link href={""} className="px-5 py-2 bg-[#fff]/40 text-white rounded-lg text-base self-start absolute top-[50px] flex flex-row items-center justify-between w-32"><BiLeftArrowAlt className="text-3xl" /> Retour</Link>

                <div className="flex w-[80%] flex-col items-center justify-start top-[200px] z-10 relative top-[200px]">
                    <section className="flex w-full flex-col items-start justify-start bg-white px-[40px] py-[40px] rounded-xl">
                        <span className="flex w-full flex-row items-center justify-between mb-3">
                            <h1 className="text-4xl font-semibold text-black">Découvrir React Native</h1>
                        </span>
                        <p className="text-sm">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin mollis vestibulum nisi a tristique. Proin tincidunt diam et velit tincidunt ullamcorper. Cras ut lacus auctor, condimentum risus quis, condimentum est.</p>
                        <div className="flex flex-row justify-between w-full items-center mt-10 mb-5">
                            <span>
                                <h2 className="text-2xl text-black">Référentiel :</h2>
                                <h3 className="text-lg text-black">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h3>
                            </span>
                            {open ? <button onClick={() => setOpen(!open)}><IoChevronUpCircleSharp className="h-[60px] w-[60px] text-[#0E6073]" /></button> : <button onClick={() => setOpen(!open)}><IoChevronDownCircleSharp className="h-[60px] w-[60px] text-[#0E6073]" /></button>}
                        </div>
                        {open &&
                            <div className="flex flex-row justify-between items-center w-full mb-5">
                                <div className="max-w-[33%] border-2 rounded-t-lg">
                                    <p className="text-sm text-[#0E6073] m-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ac arcu eget metus vehicula venenatis et a nisl.</p>
                                    <div className="flex flex-row justify-between items-center w-full rounded-lg bg-[#0E6073] p-2">
                                        <span className="flex flex-row justify-between items-center">
                                            <p className="text-white text-sm">Niveau 1</p>
                                            <BiCheck className="text-white text-xl ml-1" />
                                        </span>
                                        <span className="flex flex-row justify-between items-center">
                                            <p className="text-white text-sm">Niveau 2</p>
                                            <BiCheck className="text-white text-xl ml-1" />
                                        </span>
                                        <span className="flex flex-row justify-between items-center">
                                            <p className="text-white text-sm">Niveau 3</p>
                                            <BiCheck className="text-white text-xl ml-1" />
                                        </span>
                                    </div>
                                </div>
                                <div className="max-w-[33%] border-2 rounded-t-lg">
                                    <p className="text-sm text-[#0E6073] m-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ac arcu eget metus vehicula venenatis et a nisl.</p>
                                    <div className="flex flex-row justify-between items-center w-full rounded-lg bg-[#0E6073] p-2">
                                        <span className="flex flex-row justify-between items-center">
                                            <p className="text-white text-sm">Niveau 1</p>
                                            <BiCheck className="text-white text-xl ml-1" />
                                        </span>
                                        <span className="flex flex-row justify-between items-center">
                                            <p className="text-white text-sm">Niveau 2</p>
                                            <BiCheck className="text-white text-xl ml-1" />
                                        </span>
                                        <span className="flex flex-row justify-between items-center">
                                            <p className="text-white text-sm">Niveau 3</p>
                                            <BiCheck className="text-white text-xl ml-1" />
                                        </span>
                                    </div>
                                </div>
                                <div className="max-w-[33%] border-2 rounded-t-lg">
                                    <p className="text-sm text-[#0E6073] m-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ac arcu eget metus vehicula venenatis et a nisl.</p>
                                    <div className="flex flex-row justify-between items-center w-full rounded-lg bg-[#0E6073] p-2">
                                        <span className="flex flex-row justify-between items-center">
                                            <p className="text-white text-sm">Niveau 1</p>
                                            <BiCheck className="text-white text-xl ml-1" />
                                        </span>
                                        <span className="flex flex-row justify-between items-center">
                                            <p className="text-white text-sm">Niveau 2</p>
                                            <BiCheck className="text-white text-xl ml-1" />
                                        </span>
                                        <span className="flex flex-row justify-between items-center">
                                            <p className="text-white text-sm">Niveau 3</p>
                                            <BiCheck className="text-white text-xl ml-1" />
                                        </span>
                                    </div>
                                </div>
                            </div>
                        }
                        <h2 className="text-2xl text-black mt-5">Contexte du projet</h2>
                        <p className="text-sm">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin mollis vestibulum nisi a tristique. Proin tincidunt diam et velit tincidunt ullamcorper. Cras ut lacus auctor, condimentum risus quis, condimentum est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis posuere vel dolor sit amet dapibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam in eros eget purus suscipit viverra. Curabitur vel dolor porta, tristique sem in, vehicula metus. Nunc vulputate a mi ut convallis. Pellentesque tortor tellus, semper at urna et, gravida vestibulum lectus.
                            <br />
                            <br />
                            Phasellus dignissim sapien nunc, ac congue est iaculis id. Vestibulum vitae egestas tortor, a fermentum lectus. Proin ut dolor id enim lobortis elementum et eu libero.
                        </p>
                    </section>
                    <section className="flex w-full flex-col items-start justify-start bg-white px-[40px] py-[40px] rounded-xl mt-3">
                        <h1 className="text-4xl font-semibold text-black">Modalités</h1>
                        <h2 className="text-2xl text-black mt-10">Modalités pédagogiques</h2>
                        <p className="text-sm">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin mollis vestibulum nisi a tristique. Proin tincidunt diam et velit tincidunt ullamcorper. Cras ut lacus auctor, condimentum risus quis, condimentum est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis posuere vel dolor sit amet dapibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam in eros eget purus suscipit viverra.
                        </p>
                        <h2 className="text-2xl text-black mt-10">Modalités d&apos;évaluation</h2>
                        <p className="text-sm">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin mollis vestibulum nisi a tristique. Proin tincidunt diam et velit tincidunt ullamcorper. Cras ut lacus auctor, condimentum risus quis, condimentum est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis posuere vel dolor sit amet dapibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam in eros eget purus suscipit viverra.
                        </p>
                        <h2 className="text-2xl text-black mt-10">Livrables</h2>
                        <p className="text-sm">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin mollis vestibulum nisi a tristique. Proin tincidunt diam et velit tincidunt ullamcorper.
                        </p>
                        <h2 className="text-2xl text-black mt-10">Critères de performance</h2>
                        <p className="text-sm">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin mollis vestibulum nisi a tristique. Proin tincidunt diam et velit tincidunt ullamcorper. Cras ut lacus auctor, condimentum risus quis, condimentum est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis posuere vel dolor sit amet dapibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam in eros eget purus suscipit viverra.
                        </p>
                    </section>

                    <section className="flex w-full flex-col items-start justify-start bg-white px-[40px] py-[40px] rounded-xl mt-3">
                        <h1 className="text-4xl font-semibold text-black">Ressources</h1>
                        <div className="flex flex-row flex-wrap">
                            <button className="bg-[#0E6073] py-3 px-8 rounded-full flex flex-row items-center justify-center mt-3 mx-1">
                                <BiLink className="text-2xl text-white mr-1" />
                                <p className="text-sm text-white">https://test.com</p>
                            </button>
                            <button className="bg-[#0E6073] py-3 px-8 rounded-full flex flex-row items-center justify-center mt-3 mx-1">
                                <BiLink className="text-2xl text-white mr-1" />
                                <p className="text-sm text-white">https://test.com</p>
                            </button>
                            <button className="bg-[#0E6073] py-3 px-8 rounded-full flex flex-row items-center justify-center mt-3 mx-1">
                                <BiLink className="text-2xl text-white mr-1" />
                                <p className="text-sm text-white">https://test.com</p>
                            </button>
                            <button className="bg-[#0E6073] py-3 px-8 rounded-full flex flex-row items-center justify-center mt-3 mx-1">
                                <BiLink className="text-2xl text-white mr-1" />
                                <p className="text-sm text-white">https://test.com</p>
                            </button>
                            <button className="bg-[#0E6073] py-3 px-8 rounded-full flex flex-row items-center justify-center mt-3 mx-1">
                                <BiLink className="text-2xl text-white mr-1" />
                                <p className="text-sm text-white">https://test.com</p>
                            </button>
                            <button className="bg-[#0E6073] py-3 px-8 rounded-full flex flex-row items-center justify-center mt-3 mx-1">
                                <BiLink className="text-2xl text-white mr-1" />
                                <p className="text-sm text-white">https://test.com</p>
                            </button>

                        </div>
                    </section>
                </div>

                <Notifs />
                <NavBar />
            </main>
        </>
    );
};

export default Brief;