import { GetServerSideProps, type NextPage } from "next";
import { getSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { type Session as SessionAuth } from 'next-auth'

import NavBar from "~/pages/components/navbar";
import { BiSearch } from "react-icons/bi";
import Header from "../components/navbarhorizontal";
import Promo from "../components/promo";
import Notifs from "../components/notifs";


export const getServerSideProps: GetServerSideProps<{
    session: SessionAuth
}> = async function (context) {
    const session = await getSession(context)

    if (!session) {
        return {
            redirect: {
                destination: '/login',
                permanent: false,
            },
        }
    }

    return {
        props: { session }
    }
};

const indexBrief: NextPage = () => {

    return (
        <>
            <Head>
                <title>Gestion de OktoBrief</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-start justify-start bg-[#F3F3F3] pl-[100px]">
                <div className="flex min-h-screen w-full flex-col items-center justify-start px-[10%] pt-[40px] mt-12">
                    <span className="flex w-full flex-row items-center justify-between mb-10">
                        <h1 className="text-4xl font-extrabold text-black w-full">Mes projets</h1>
                        <div className="pr-[1rem] rounded-full bg-white shadow-[inset_4px_4px_12px_4px_rgba(0,0,0,0.25)] w-[40%] flex flex-row justify-between items-center">
                            <BiSearch className="text-3xl text-black ml-4" />
                            <input
                            type='text'
                            name="promoDateStart"
                            className="pr-[1rem] pl-1 py-3 w-full bg-transparent"
                            autoComplete="off"
                            />
                        </div>
                    </span>

                    <div className="flex w-full flex-col items-center justify-start bg-white rounded-lg px-[40px] py-[40px] mb-5">
                        <span className="flex w-full flex-row items-center justify-between mb-3">
                        <h2 className="text-2xl text-black">Les projets de ma promo</h2>
                        <span className="flex w-[45%] flex-row items-center justify-end">
                            <input
                                type='text'
                                name="leconTitle"
                                className="px-[1rem] py-3 rounded-full bg-white shadow-[inset_4px_5px_12px_6px_rgba(0,0,0,0.25)] w-[50%] mr-2"
                                autoComplete="off"
                            />
                            <button className="flex flex-row items-center justify-between px-5 py-3 bg-[#2EA3A5] hover:bg-[#288F90] text-white rounded-lg text-base">
                            Créer un projet
                            </button>
                        </span>
                        </span>
                        <div className="flex flex-row flex-wrap justify-between w-full">
                        <Link className="flex flex-col w-[33%] max-w-[500px] rounded-lg h-[400px] my-1 shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)]" href={""}>
                            <img src="/promo.jpeg" className="w-[100%] max-h-[200px] bg-center bg-cover mr-5 rounded-t-lg" alt="Image de la promo sélectionnée"/>
                            <div className="m-5 text-start">
                            <h3 className="text-lg text-black">Découvrir React Native</h3>
                            <p className="text-sm text-black">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sodales euismod blandit.</p>
                            <span className="flex flex-row justify-end items-center w-full mt-5">
                                <img src="/userPFP.png" className="w-12 h-12 rounded-full object-cover mr-3" alt="Photo de profil utilisateur"/>
                                <p className="text-sm text-black">Lorem ipsum</p>
                            </span>
                            </div>
                        </Link>

                        <Link className="flex flex-col w-[33%] max-w-[500px] rounded-lg h-[400px] my-1 shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)]" href={""}>
                            <img src="/promo.jpeg" className="w-[100%] max-h-[200px] bg-center bg-cover mr-5 rounded-t-lg" alt="Image de la promo sélectionnée"/>
                            <div className="m-5 text-start">
                            <h3 className="text-lg text-black">Découvrir React Native</h3>
                            <p className="text-sm text-black">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sodales euismod blandit.</p>
                            <span className="flex flex-row justify-end items-center w-full mt-5">
                                <img src="/userPFP.png" className="w-12 h-12 rounded-full object-cover mr-3" alt="Photo de profil utilisateur"/>
                                <p className="text-sm text-black">Lorem ipsum</p>
                            </span>
                            </div>
                        </Link>

                        <Link className="flex flex-col w-[33%] max-w-[500px] rounded-lg h-[400px] my-1 shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)]" href={""}>
                            <img src="/promo.jpeg" className="w-[100%] max-h-[200px] bg-center bg-cover mr-5 rounded-t-lg" alt="Image de la promo sélectionnée"/>
                            <div className="m-5 text-start">
                            <h3 className="text-lg text-black">Découvrir React Native</h3>
                            <p className="text-sm text-black">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sodales euismod blandit.</p>
                            <span className="flex flex-row justify-end items-center w-full mt-5">
                                <img src="/userPFP.png" className="w-12 h-12 rounded-full object-cover mr-3" alt="Photo de profil utilisateur"/>
                                <p className="text-sm text-black">Lorem ipsum</p>
                            </span>
                            </div>
                        </Link>

                        <Link className="flex flex-col w-[33%] max-w-[500px] rounded-lg h-[400px] my-1 shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)]" href={""}>
                            <img src="/promo.jpeg" className="w-[100%] max-h-[200px] bg-center bg-cover mr-5 rounded-t-lg" alt="Image de la promo sélectionnée"/>
                            <div className="m-5 text-start">
                            <h3 className="text-lg text-black">Découvrir React Native</h3>
                            <p className="text-sm text-black">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sodales euismod blandit.</p>
                            <span className="flex flex-row justify-end items-center w-full mt-5">
                                <img src="/userPFP.png" className="w-12 h-12 rounded-full object-cover mr-3" alt="Photo de profil utilisateur"/>
                                <p className="text-sm text-black">Lorem ipsum</p>
                            </span>
                            </div>
                        </Link>

                        <Link className="flex flex-col w-[33%] max-w-[500px] rounded-lg h-[400px] my-1 shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)]" href={""}>
                            <img src="/promo.jpeg" className="w-[100%] max-h-[200px] bg-center bg-cover mr-5 rounded-t-lg" alt="Image de la promo sélectionnée"/>
                            <div className="m-5 text-start">
                            <h3 className="text-lg text-black">Découvrir React Native</h3>
                            <p className="text-sm text-black">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sodales euismod blandit.</p>
                            <span className="flex flex-row justify-end items-center w-full mt-5">
                                <img src="/userPFP.png" className="w-12 h-12 rounded-full object-cover mr-3" alt="Photo de profil utilisateur"/>
                                <p className="text-sm text-black">Lorem ipsum</p>
                            </span>
                            </div>
                        </Link>

                        <Link className="flex flex-col w-[33%] max-w-[500px] rounded-lg h-[400px] my-1 shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)]" href={""}>
                            <img src="/promo.jpeg" className="w-[100%] max-h-[200px] bg-center bg-cover mr-5 rounded-t-lg" alt="Image de la promo sélectionnée"/>
                            <div className="m-5 text-start">
                            <h3 className="text-lg text-black">Découvrir React Native</h3>
                            <p className="text-sm text-black">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sodales euismod blandit.</p>
                            <span className="flex flex-row justify-end items-center w-full mt-5">
                                <img src="/userPFP.png" className="w-12 h-12 rounded-full object-cover mr-3" alt="Photo de profil utilisateur"/>
                                <p className="text-sm text-black">Lorem ipsum</p>
                            </span>
                            </div>
                        </Link>

                        <Link className="flex flex-col w-[33%] max-w-[500px] rounded-lg h-[400px] my-1 shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)]" href={""}>
                            <img src="/promo.jpeg" className="w-[100%] max-h-[200px] bg-center bg-cover mr-5 rounded-t-lg" alt="Image de la promo sélectionnée"/>
                            <div className="m-5 text-start">
                            <h3 className="text-lg text-black">Découvrir React Native</h3>
                            <p className="text-sm text-black">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sodales euismod blandit.</p>
                            <span className="flex flex-row justify-end items-center w-full mt-5">
                                <img src="/userPFP.png" className="w-12 h-12 rounded-full object-cover mr-3" alt="Photo de profil utilisateur"/>
                                <p className="text-sm text-black">Lorem ipsum</p>
                            </span>
                            </div>
                        </Link>
                        </div>
                    </div>

                </div>

                <Header selected={1} />
                
                <Notifs />
                <NavBar />
            </main>
        </>
    );
};

export default indexBrief;