import { GetServerSideProps, type NextPage } from "next";
import Head from "next/head";
import { getSession, signIn, signOut, useSession } from "next-auth/react";
import { type Session as SessionAuth } from 'next-auth'

import { api } from "~/utils/api";

import dynamic from "next/dynamic";
import { useState } from "react";

import Link from "next/link";
import { BiChevronDown, BiClipboard, BiListCheck } from "react-icons/bi";
import { FaInbox, FaOctopusDeploy } from "react-icons/fa";
import NavBar from "~/pages/components/navbar";

const QuillNoSSRWrapper = dynamic(import('react-quill'), {
    ssr: false,
    loading: () => <p>Loading ...</p>,
})

export const getServerSideProps: GetServerSideProps<{
    session: SessionAuth
}> = async function (context) {
    const session = await getSession(context)
    const admin = session?.user.superadmin

    if (!session || !admin) {
        return {
            redirect: {
                destination: '/',
                permanent: false,
            },
        }
    }

    return {
        props: { session }
    }
};

const AddReferentiel: NextPage = () => {

    return (
        <>
            <Head>
                <title>Créer une Formation</title>
                <meta name="description" content="Generated by create-t3-app" />

            </Head>
            <main className="flex min-h-screen flex-col items-start justify-start bg-[#F3F3F3] pl-[100px]">
                <h1 className="text-4xl font-extrabold text-black w-full">Créer un référentiel</h1>

                <div className="flex w-full flex-col items-center justify-start bg-white px-[40px] py-[40px] mb-5 gap-5 rounded-xl">
                    <span className="flex w-full flex-row items-center justify-between mb-3">
                        <h2 className="text-2xl text-black">Données sur la plateforme</h2>
                    </span>

                    <div className="flex w-full flex-row items-center justify-center gap-16">
                        <div className="flex flex-col items-center justify-center">
                            <h3 className="text-7xl mb-2 text-[#2EA3A5]">76</h3>
                            <p className="text-3xl mb-5 text-[#0E6073] font-[700]">Apprenants</p>
                        </div>
                        <div className="flex flex-col items-center justify-center">
                            <h3 className="text-7xl mb-2 text-[#2EA3A5]">26</h3>
                            <p className="text-3xl mb-5 text-[#0E6073] font-[700]">Promos créées</p>
                        </div>
                        <div className="flex flex-col items-center justify-center">
                            <h3 className="text-7xl mb-2 text-[#2EA3A5]">62</h3>
                            <p className="text-3xl mb-5 text-[#0E6073] font-[700]">Projets créés</p>
                        </div>
                    </div>
                </div>
                <div className="flex min-h-screen w-full flex-col items-center justify-start px-[25px] pt-[40px]">
                </div>

                <NavBar />
            </main>

        </>
    );
};

export default AddReferentiel;